name: Docker Compose CI Validation

on:
   push:
      branches:
         - main

   pull_request:
      branches:
         - main

jobs:
   validate:
      runs-on: ubuntu-latest


      steps:
         - name: Descargar repositorio
           uses: actions/checkout@v4

         - name: Validar Docker Compose
           run: docker compose config
